name: "cccc-action"
author: sarnold
description: "Generate useful metrics for C, C++, and Java code"

inputs:
  github_token:
    description: "GITHUB_TOKEN secret < automatically provided by Github , you don't need to set up >"
    required: true

  report_type:
    description: "Report type: xml | HTML"
    default: "html"
    required: false

  target_branch:
    description: "Branch that the action will target. Defaults to the current branch."
    default: ""
    required: false

  pull_request_branch:
    description: "Branch that the action will target on pull_request. Defaults to GITHUB_BASE_REF."
    default: ""
    required: false

  target_repository:
    description: "Repository that the report will be pushed to. Defaults to the current repository."
    default: ""
    required: false

  pull_request_repository:
    description: "Repository that the action will target on pull_request. Defaults to TARGET_REPOSITORY"
    default: ""
    required: false

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "alert-octagon"
  color: "red"
