name: option-tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]


jobs:
  cccc_test:
    runs-on: ubuntu-latest
    name: Test options
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: cccc action step (all sources)
        uses: ./ # Uses an action in the root directory
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          source_dir: 'tests'

      - name: cccc action step with options
        uses: ./ # Uses an action in the root directory
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          target_branch: test-branch
          file_extensions: |
            .h
            .cc

      - name: upload report
        uses: actions/upload-artifact@v2
        with:
          name: metrics
          path: ./metrics
